// Generated by https://quicktype.io

export interface PokemonPaginetedResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}

export interface SimplePokemon {
  id: String;
  name: string;
  picture: string;
  color?: string;
}
